---
# tasks file for install_nginx
- name: install system updates for centos systems
  yum: 
    name: '*' 
    update_cache: yes
  when: 
    ansible_distribution == "CentOS"
  become: yes

- name: install system updates for ubuntu systems
  apt:
    upgrade: dist
    update_cache: yes
  when:
    ansible_distribution == "Ubuntu"
  become: yes

- name: ensure nginx is at the latest version for ubuntu systems
  apt:
    name: nginx
  when:
    ansible_distribution == "Ubuntu"
  become: yes

- name: ensure epel-relese for the centos systems
  yum:
    name: epel-release
  when:
    ansible_distribution == "CentOS"
  become: yes

- name: ensure nginx is at the latest version for centos systems
  yum:
    name: nginx
  when:
    ansible_distribution == "CentOS"
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes
  ignore_errors: yes
