---
# tasks file for install_nginx
- include: "{{ ansible_distribution | lower }}.yml"
  notify: start nginx

- name: copy nginx config for Ubuntu
  vars:
    user: www-data
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: ansible_distribution == "Ubuntu"

- name: copy nginx config file for CentOS
  vars:
    user: nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: ansible_distribution == "CentOS"
